#!/bin/bash
# =============================================================================
# SYNCLEDGER - EC2 BOOTSTRAP SCRIPT
# Installs Docker, loads secrets, deploys app via Docker Compose
# =============================================================================
set -euo pipefail

exec > >(tee /var/log/syncledger-setup.log) 2>&1
echo "=========================================="
echo "SyncLedger Setup - ${environment} - $(date)"
echo "=========================================="

# ---- System Updates ----
dnf update -y
dnf install -y docker git jq

# ---- Install Docker Compose v2 ----
DOCKER_COMPOSE_VERSION="v2.29.0"
ARCH=$(uname -m)
case $ARCH in
  x86_64)  COMPOSE_ARCH="x86_64" ;;
  aarch64) COMPOSE_ARCH="aarch64" ;;
  *)       COMPOSE_ARCH="x86_64" ;;
esac
curl -SL "https://github.com/docker/compose/releases/download/$${DOCKER_COMPOSE_VERSION}/docker-compose-linux-$${COMPOSE_ARCH}" \
  -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose

# ---- Start Docker ----
systemctl enable docker
systemctl start docker
usermod -aG docker ec2-user

# ---- Create swap (2GB) for small instances ----
if [ ! -f /swapfile ]; then
  dd if=/dev/zero of=/swapfile bs=1M count=2048
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  echo '/swapfile swap swap defaults 0 0' >> /etc/fstab
fi

# ---- Create app directory ----
mkdir -p /opt/syncledger
cd /opt/syncledger

# ---- Download docker-compose from S3 ----
aws s3 cp "s3://${s3_config_bucket}/${environment}/docker-compose.yml" /opt/syncledger/docker-compose.yml \
  --region ${region}

# ---- Load secrets from Secrets Manager ----
echo "Loading application secrets..."
APP_SECRET=$(aws secretsmanager get-secret-value \
  --secret-id "${project_name}/${environment}/app-config" \
  --region ${region} \
  --query 'SecretString' --output text)

# Parse JSON secret into .env file
cat > /opt/syncledger/.env <<ENVEOF
# Auto-generated by user_data.sh - DO NOT EDIT
# Environment: ${environment}
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Database (RDS)
DB_HOST=${db_host}
DB_PORT=${db_port}
DB_NAME=${db_name}
DB_USERNAME=$(echo "$APP_SECRET" | jq -r '.DB_USERNAME')
DB_PASSWORD=$(echo "$APP_SECRET" | jq -r '.DB_PASSWORD')

# Application
JWT_SECRET=$(echo "$APP_SECRET" | jq -r '.JWT_SECRET')
ENVIRONMENT=${environment}
SPRING_PROFILES_ACTIVE=docker
STORAGE_TYPE=s3

# AWS
AWS_REGION=${region}
S3_BUCKET_NAME=${s3_storage_bucket}

# OpenAI
OPENAI_API_KEY=$(echo "$APP_SECRET" | jq -r '.OPENAI_API_KEY')
OPENAI_VISION_MODEL=gpt-4o
OPENAI_TEXT_MODEL=gpt-4o

# Docker Image
GHCR_OWNER=${ghcr_owner}
IMAGE_TAG=${image_tag}

# Email Polling
EMAIL_POLLING_ENABLED=$(echo "$APP_SECRET" | jq -r '.EMAIL_POLLING_ENABLED')
AZURE_CLIENT_ID=$(echo "$APP_SECRET" | jq -r '.AZURE_CLIENT_ID')
AZURE_CLIENT_SECRET=$(echo "$APP_SECRET" | jq -r '.AZURE_CLIENT_SECRET')
AZURE_TENANT_ID=$(echo "$APP_SECRET" | jq -r '.AZURE_TENANT_ID')

# CORS
CORS_ALLOWED_ORIGINS=$(echo "$APP_SECRET" | jq -r '.CORS_ALLOWED_ORIGINS')

# Encryption
ENCRYPTION_MASTER_KEY=$(echo "$APP_SECRET" | jq -r '.ENCRYPTION_MASTER_KEY // ""')
ENVEOF

chmod 600 /opt/syncledger/.env

# ---- Login to GHCR ----
echo "Logging into GitHub Container Registry..."
GHCR_SECRET=$(aws secretsmanager get-secret-value \
  --secret-id "${project_name}/${environment}/ghcr" \
  --region ${region} \
  --query 'SecretString' --output text 2>/dev/null || echo '{}')

GHCR_USER=$(echo "$GHCR_SECRET" | jq -r '.username // empty')
GHCR_TOKEN=$(echo "$GHCR_SECRET" | jq -r '.token // empty')

if [ -n "$GHCR_TOKEN" ]; then
  echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
  echo "GHCR login successful"
else
  echo "WARNING: No GHCR credentials found. Will use public images only."
fi

# ---- Deploy ----
echo "Pulling images and starting services..."
docker-compose pull || true
docker-compose up -d --remove-orphans

# ---- Create systemd service for auto-restart ----
cat > /etc/systemd/system/syncledger.service <<'SERVICEEOF'
[Unit]
Description=SyncLedger Application
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/syncledger
ExecStart=/usr/local/bin/docker-compose up -d
ExecStop=/usr/local/bin/docker-compose down
EnvironmentFile=/opt/syncledger/.env

[Install]
WantedBy=multi-user.target
SERVICEEOF

systemctl daemon-reload
systemctl enable syncledger.service

# ---- Health check ----
echo "Waiting for application to start..."
for i in $(seq 1 30); do
  HTTP_CODE=$(curl -s -o /dev/null -w "%%{http_code}" http://localhost/actuator/health 2>/dev/null || echo "000")
  if [ "$HTTP_CODE" = "200" ]; then
    echo "Application is healthy! (attempt $i)"
    break
  fi
  echo "  Attempt $i/30 - HTTP $HTTP_CODE, waiting 10s..."
  sleep 10
done

echo "=========================================="
echo "SyncLedger Setup Complete - $(date)"
echo "Environment: ${environment}"
echo "RDS Host: ${db_host}"
echo "S3 Bucket: ${s3_storage_bucket}"
echo "=========================================="
